### PR TITLE
Fix some projecthydra references for test runs, dependency checks

### PR DESCRIPTION
**Pull request by cazzerson**

### CODE REVIEW

**Comment by jcoyne** [comment]
@cazzerson Your github profile says NCSU, but you're now at UNC, right?   We don't yet have an individual contributor license agreement for you. We'd be most happy to accept this PR if you could fill one out. https://wiki.duraspace.org/download/attachments/31662457/Hydra%20Project%20Contributor%20License%20Agreement%20for%20Individuals-20121216.pdf  
Please send the agreement to legal@projecthydra.org  Thank you.

**Comment by cazzerson** [comment]
@jcoyne Yikes, fixed that. I thought we had submitted a batch of CLAs from UNC about a month ago. Do you have any on record?

**Comment by jcoyne** [comment]
@cazzerson we have a corporate (cCLA) for UNC, but not one for you as an individual.

**Comment by jcoyne** [comment]
Okay, looks like CLA issues are resolved.

**Pull request merged**
